# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.cache/wt} [current_project]
set_property parent.project_path {C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:basys3:part0:1.1 [current_project]
set_property ip_output_repo {c:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  {C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.srcs/sources_1/imports/operadorFloatingPoint/fpupack.vhd}
  {C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.srcs/sources_1/imports/simauto/addsubfsm_v6.vhd}
  {C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.srcs/sources_1/imports/simauto/entities.vhd}
  {C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.srcs/sources_1/imports/simauto/multiplierfsm_v2.vhd}
  {C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.srcs/sources_1/imports/simauto/neuronio.vhd}
  {C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.srcs/sources_1/new/ex3_neuronioGMBII.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.srcs/constrs_1/imports/ping_pong/basys3.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/Misael/Desktop/UNB/7 SEMESTRE/PROJETO DE CIRCUITOS RECONFIGURAVEIS/Lista1/ex3_neuronioGMBII/ex3_neuronioGMBII.srcs/constrs_1/imports/ping_pong/basys3.xdc}}]


synth_design -top ex3_neuronioGMBII -part xc7a35tcpg236-1


write_checkpoint -force -noxdef ex3_neuronioGMBII.dcp

catch { report_utilization -file ex3_neuronioGMBII_utilization_synth.rpt -pb ex3_neuronioGMBII_utilization_synth.pb }
